app/routes/users_route.py
import os
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required,current_user
from werkzeug.utils import secure_filename
from app.models.users import Users
from app import db  # Importamos `app` para acceder a la configuración


bp = Blueprint('users', __name__)

# Configuración para la subida de imágenes
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
UPLOAD_FOLDER = os.path.join(os.getcwd(), 'app', 'static\imagenes')  # Ruta absoluta

# Verificar que la carpeta existe, si no, crearla
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

def allowed_file(filename):
    """Verifica si la extensión del archivo es válida."""
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@bp.route('/users')
def index():
    data = Users.query.all()
    if current_user.tipousu == 1 : #administrador
        return render_template('usuarios/index.html', data=data,datausu=current_user)
    else:
        return redirect(url_for('auth.dashboard')) 
@bp.route('/users/add', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'POST':
        #print("📩 Datos recibidos:", request.form)
        #print("📂 Archivos recibidos:", request.files)

        nameuser = request.form['nameuser']
        clave = request.form['claveuser']
        vclave = request.form['vclaveuser']
        nombre = request.form['nombre']
        cedula = request.form['cedula']
        telefono = request.form['telefono']
        correo = request.form['correo']
        tipousu = request.form['tipousu']
        # Usuario con imagen predeterminada
        new_user = Users(passworduser=clave, nameuser=nameuser, imgper="usuario.png",nombre=nombre,
                         cedula=cedula,telefono=telefono,correo=correo,tipousu=tipousu)

        # Verificar si 'img1' está en los archivos recibidos
        #if 'img1' not in request.files:
            #flash("⚠ No se encontró la imagen en la solicitud", "error")
            #return redirect(request.url)

        file = request.files['img1']

        #if file.filename == '':
            #flash("⚠ No se seleccionó ninguna imagen", "error")
            #return redirect(request.url)

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)  # Nombre seguro
            filepath = os.path.join(UPLOAD_FOLDER, filename)
            
            print(f"📁 Guardando imagen en: {filepath}")  # Depuración

            try:
                file.save(filepath)  # Guarda la imagen
                print(f"✅ Imagen {filename} guardada correctamente")
                new_user.imgper = filename  # Guarda solo el nombre en la BD
            except Exception as e:
                print(f"❌ Error al guardar la imagen: {str(e)}")
                flash(f"❌ Error al guardar la imagen: {str(e)}", "error")

        # Guardar usuario en la base de datos
        db.session.add(new_user)
        db.session.commit()
        flash('✅ Usuario creado correctamente')
        
        return redirect(url_for('users.index'))  # Redirigir a la lista de usuarios

    return render_template('usuarios/add.html')




@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    user = Users.query.get_or_404(id)

    if request.method == 'POST':
        user.nameuser = request.form['nameuser']
        user.nombre = request.form['nombre']
        user.cedula = request.form['cedula']
        user.telefono = request.form['telefono']
        user.correo = request.form['correo']
        user.tipousu = request.form['tipousu']
        db.session.commit()        
        return redirect(url_for('users.index'))

    return render_template('usuarios/edit.html', datauser=user)



@bp.route('/delete/<int:id>')
def delete(id):
    user = Users.query.get_or_404(id)
    db.session.delete(user)
    db.session.commit()

    return redirect(url_for('users.index'))

app/templates/usuarios/add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style1.css') }}">
    <title>Administrar Usuarios</title>
</head>

<body>
    <h1>Agregar Usuario</h1>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="flash-message alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="flash-message alert alert-{{ category }}" id = "mensaje"></div>
    <form action="{{ url_for('users.add') }}" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nameuser" placeholder="Nombre usuario" required>
        </div>
        
        <div class="form-group">
            <label for="claveuser">Clave:</label>
            <input type="password" id="claveuser" name="claveuser" placeholder="contraseña" required>
        </div>
        
        <div class="form-group">
            <label for="vclaveuser">Verifique su clave:</label>
            <input type="password" id="vclaveuser" name="vclaveuser" placeholder="verifique su contraseña" required oninput="validarconcidencia(this)">
        </div>

    
        <div class="form-group">
            <input type="text" name="nombre" placeholder="Nombre Completo Usuario">
        </div>

        <div class="form-group">
            <input type="text" name="telefono" placeholder="Teléfono">
        </div>

        <div class="form-group">
            <input type="text" name="cedula" placeholder="Cédula" required>
        </div>

        <div class="form-group">
            <input type="text" name="correo" placeholder="Correo">
        </div>

        <div class="form-group">
            <label for="img1">Imagen de Perfil:</label>
            <input type="file" id="img1" name="img1" accept="image/*">
        </div>
        <br><br>
        <label for="tipousuario">tipo usuario:</label>
        <select id="tipousu" name="tipousu"  class="form-select rounded-pill">
                <option value= 1 >Administrador</option>
                <option value= 2 >cliente</option>
                <option value= 3 >Proveedor</option>
        </select>

        <br><br>
        <button  type="submit">Agregar Usuario</button>
        <a class="button1"  href="{{ url_for('users.index') }}">cancelar</a>


    </form>

    <script>
        function validarconcidencia(input) {
            console.log("Entra a la funcion");
            const mensajeDiv = document.getElementById("mensaje");
            if (input.value !== document.getElementById('claveuser').value) {
                mensajeDiv.innerText = "Las contraseñas no coinciden.";
                mensajeDiv.style.display = "block"; // Show the message
                input.setCustomValidity('Las contraseñas no coinciden.');
            } else {
                mensajeDiv.innerText = "";
                mensajeDiv.style.display = "none"; // Hide the message
                input.setCustomValidity('');
            }
        }

        function validarFormulario() {
            const clave = document.getElementById('claveuser').value;
            const verificarClave = document.getElementById('vclaveuser').value;

            if (clave !== verificarClave) {
                alert("Las contraseñas no coinciden.");
                return false; // Prevent form submission
            }
            return true;
        }
    </script>
</body>

</html>

app/templates/usuarios/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style1.css') }}">
    <title>Administrar usuarios</title>
</head>
<body>
    <h1>Editar Usuarios</h1>
    <form action="{{ url_for('users.edit', id=datauser.iduser) }}" method="post">
        <label for="nombre">Nombre usuario:</label>
        <input type="text" id="nameuser" name="nameuser" value="{{ datauser.nameuser }}" required>
        <label for="nombre">Nombre completo:</label>
        <input type="text" id="nombre" name="nombre" value="{{ datauser.nombre }}" required placeholder="Nombre usuario">

        <div class="form-group">
            <label for="telefono">telefono:</label>
            <input type="text" name="telefono" value="{{ datauser.telefono }}" placeholder="Teléfono">
        </div>

        <div class="form-group">
            <label for="cedula">cedula:</label>
            <input type="text" name="cedula" value="{{ datauser.cedula }}" placeholder="Cédula" required>
        </div>

        <div class="form-group">
            <label for="correo">correo:</label>
            <input type="email" name="correo" value="{{ datauser.correo }}" placeholder="Correo">
        </div>

        <div class="form-group">
            <label for="img1">Imagen de Perfil:</label>
            <input type="file" id="img1" name="img1" accept="image/*">
        </div>
        <br><br>

        <label for="tipousuario">tipo usuario:</label>
        <select id="tipousu" name="tipousu"  class="form-select rounded-pill">
                <option value= 1 {% if datauser.tipousu == 1 %} selected {%endif%}  >Administrador</option>
                <option value= 2 {% if datauser.tipousu == 2 %} selected {%endif%}>cliente</option>
                <option value= 3 {% if datauser.tipousu == 3 %} selected {%endif%}>Proveedor</option>
        </select>
        <br><br>

        <button type="submit">Actualizar Usuarios</button>
        <a class="button1" href="{{ url_for('users.index') }}">Cancelar</a>

    </form>
</body>
</html>

app/templates/usuarios/index.html
{% extends "baseb.html" %}
{% block titulo_pagina %}Lista de Usuarios{% endblock %}
{% block content %}
<a class="btn btn-primary btn-sm mb-1"href="{{ url_for('users.add') }}">Agregar Usuario</a>
<a class="btn btn-sm btn-success mb-1"href="{{ url_for('auth.dashboard') }}">Regresar</a>

<table>
    <tr>
        <th>ID</th>
        <th>nombre</th>
        <th>clave</th>
        <th>imagen perfil</th>
        <th>acciones</th>
    </tr>
    {% for usuario in data %}
    <tr>
        <td>{{ usuario.iduser }}</td>
        <td>{{ usuario.nameuser }}</td>
        <td>{{ usuario.passworduser }}</td>
        <td>{{ usuario.imgper }}</td>
        <td>
            <a href="{{ url_for('users.edit', id=usuario.iduser) }}">Editar</a>
            <a href="{{ url_for('users.delete', id=usuario.iduser) }}">Eliminar</a>
            {#<a href="{{ url_for('departamentos.list', id=depart.idDepartment) }}">Listar empleados</a>
            #}
            <!-- Agrega aquí el enlace para eliminar -->

        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}